parameters:
    database_driver:   pdo_mysql
    database_host:     sql206.your-server.de
    database_port:     ~
    database_name:     bsbsbs
    database_user:     bsbsbs_w
    database_password: wUzCDi2s

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
