Tag:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  manyToOne:
    Group:
      targetEntity: TagGroup
      inversedBy: Tags
      orphanRemoval: true
      joinColumns:
        tag_group_id:
          referencedColumnName: id
          nullable: false
          onDelete: CASCADE
          onUpdate: CASCADE
  manyToMany:
    Tricks:
      targetEntity: Trick
      mappedBy: Tags
