Bs\VideoBundle\Entity\TagGroup:
  type: entity
  fields:
    id:
      id: true
      generator:
        strategy: AUTO
    name:
      nullable: false
  oneToMany:
    Tags:
      targetEntity: Bs\VideoBundle\Entity\Tag
      mappedBy: Group
