TagGroup:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    name:
      type: string
      nullable: false
  oneToMany:
    Tags:
      targetEntity: Tag
      mappedBy: Group
      orphanRemoval: true
