Bs\VideoBundle\Entity\TagGroup:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        name:
            type: string
            nullable: false
        weight:
            type: integer
            nullable: true
    oneToMany:
        Tags:
            targetEntity: Bs\VideoBundle\Entity\Tag
            mappedBy: Group
            orphanRemoval: true
