Bs\VideoBundle\Entity\Trick:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    start:
      type: integer
      nullable: false
    end:
      type: integer
      nullable: false
  manyToOne:
    Video:
      targetEntity: Bs\VideoBundle\Entity\Video
      inversedBy: Tricks
      joinColumns:
        video_id:
          referencedColumnName: id
          nullable: false
  manyToMany:
    Tags:
      targetEntity: Tag
      inversedBy: Tricks
      joinTable:
        name: TrickTag
        joinColumns:
          trick_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id
            nullable: false
