User:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
  oneToMany:
    Videos:
      targetEntity: Video
      mappedBy: Uploader
    TricksUploaded:
      targetEntity: Trick
      mappedBy: Uploader
    TricksMade:
      targetEntity: Trick
      mappedBy: Rider
