Bs\VideoBundle\Entity\User:
    type: entity
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        Videos:
            targetEntity: Bs\VideoBundle\Entity\Video
            mappedBy: Uploader
        TricksUploaded:
            targetEntity: Bs\VideoBundle\Entity\Trick
            mappedBy: Uploader
        TricksMade:
            targetEntity: Bs\VideoBundle\Entity\Trick
            mappedBy: Rider
        comments:
            targetEntity: Bs\VideoBundle\Entity\Comment
            mappedBy: author
