Bs\VideoBundle\Entity\Video:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    vid:
      type: string
      nullable: false
    name:
      type: string
      nullable: false
    duration:
      type: decimal
      nullable: false
  oneToMany:
    Tricks:
      targetEntity: Bs\VideoBundle\Entity\Trick
      mappedBy: Video
