Bs\VideoBundle\Entity\Video:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    vid:
      type: string
      nullable: false
    name:
      type: string
      nullable: false
    duration:
      type: decimal
      nullable: false
    start:
      type: decimal
      nullable: true
    end:
      type: decimal
      nullable: true
  manyToMany:
    Tags:
      targetEntity: Tag
      mappedBy: Videos
