Video:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    service:
      type: string
      nullable: false
    vid:
      type: string
      nullable: false
    name:
      type: string
      nullable: false
    duration:
      type: decimal
      nullable: false
    created_at:
      type: datetime
      nullable: false
    views:
      type: integer
      nullable: false
  oneToMany:
    Tricks:
      targetEntity: Trick
      mappedBy: Video
      orphanRemoval: true
  manyToOne:
    Uploader:
      targetEntity: User
      inversedBy: Videos
      joinColumns:
        user_id:
          referencedColumnName: id
          nullable: false
