Bs\VideoBundle\Entity\Video:
    type: entity
    repositoryClass: Bs\VideoBundle\Entity\VideoRepository
    fields:
        id:
            id: true
            type: integer
            generator:
                strategy: AUTO
        service:
            type: string
            nullable: false
        vid:
            type: string
            nullable: false
        name:
            type: string
            nullable: false
        duration:
            type: decimal
            nullable: false
        created_at:
            type: datetime
            nullable: false
        views:
            type: integer
            nullable: false
        thumbnail:
            type: string
            nullable: false
        num_comments:
            type: integer
            nullable: false
        num_tricks:
            type: integer
            nullable: false
    oneToMany:
        Tricks:
            targetEntity: Bs\VideoBundle\Entity\Trick
            mappedBy: Video
            orphanRemoval: true
    manyToOne:
        Uploader:
            targetEntity: Bs\VideoBundle\Entity\User
            inversedBy: Videos
            joinColumns:
                user_id:
                    referencedColumnName: id
                    nullable: false
